### ISSUE TITLE
Mongo Alpine

### ISSUE THREAD

**Issue by rtmaster** [edgexfoundry/docker-edgex-mongo#10]
Would it be worth using the mongo image based on alpine?
This would reduce disk size from 370MB to 110 MB since it does not have the Debian OS additional footprint.
I am not aware of a mongo:alpine in the official repo but this one seems quite used https://hub.docker.com/r/mvertes/alpine-mongo/

**Comment by SteveOss** [comment]
The mongo support in Alpine is on the edge stream i.e. non stable. Also it is mongo version 3.6
whereas we are currently using 3.4. As a pre-requisite should probably try updating to version
3.6 first to eliminate any versioning issues.

See: https://pkgs.alpinelinux.org/package/edge/community/x86_64/mongodb

**Comment by rtmaster** [comment]
hi @SteveOss do you know any other Mongo Alpine image on dockerhub or other repository apart from the above?

**Comment by SteveOss** [comment]
Hi @rtmaster am afraid not. Am currently building Mongo from source to support 32bit ARM using
a Debian base image. If this works can try same approach with Alpine ...
