### ISSUE TITLE
Mongo Service cannot start up on arm64

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/docker-edgex-mongo#22]
In the following change, we added `mongod --smallfiles --bind_ip_all` in `launch-edgex-mongo.sh` 
https://github.com/edgexfoundry/docker-edgex-mongo/commit/2c86e5e4359367177dc339556604c3af6fb9ee2a
https://github.com/edgexfoundry/docker-edgex-mongo/blob/2c86e5e4359367177dc339556604c3af6fb9ee2a/launch-edgex-mongo.sh#L20

However, arm64 is still using Mongo v3.4.7, and it can't recognize `--bind_ip_all`, so the following error occurs

> 00:11:55 MongoDB shell version v3.4.7
> 00:11:55 Error parsing command line: unrecognised option '--bind_ip_all'
> 00:11:55 try 'mongod --help' for more information

**Comment by cloudxxx8** [comment]
This issue is blocking the blackbox test on arm64.
add @andyf1967, @frq92290 for awareness.
Thanks for @cherrycl 's investigation

**Comment by tsconn23** [comment]
@cloudxxx8 As I called out on Slack and in my PR, someone needs to work on the ARM version of the Mongo 4.x upgrade. That flag is necessary for Mongo versions later than 3.6 in which some defaults w/r/t network bindings were changed.

**Comment by cloudxxx8** [comment]
Add @jpwhitemn @jamesrgregg for awareness.  This issue is also breaking the current edinburgh image on arm64, but I saw the Mongo 4.0 change is not in edinburgh branch.  I guess the Mongo build is still running against the master branch.
