### ISSUE TITLE
Replace init_mongo.js With Go Bootstrapping Application

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/docker-edgex-mongo#32]
Currently when this container boots, a shell script uses `init_mongo.js` to initialize access credentials, collections, indexes and so forth for the Mongo database. For the Fuji release, we would like to replace this with an actual Go application. The initial work on this application to establish parity with the init_mongo.js script can be found [here](https://github.com/edgexfoundry-holding/edgex-mongo-init) in the holding area.

This issue is for moving that application into this repo in a suitable location, such as a /cmd directory. The Go application should be built into an executable as part of the Dockerfile and placed into the destination image along with Mongo. When the container boots, Mongo must come up first then the application needs to be run just as happens today.

Integration verification testing with edgex-go should also be done since that has not yet occurred with the code from the holding area.

**Comment by ernestojeda** [comment]
@tsconn23 Would this Go tool need to be versioned differently outside of the other docker-edgex-mongo deliverables? Or would it stay in lock step with it? Would it make sense to keep it in a separate repository?

**Comment by tsconn23** [comment]
It'll be a part of this repo and versioned as part of the docker-edgex-mongo image. It's simply an application that will replace the [existing javascript](https://github.com/edgexfoundry/docker-edgex-mongo/blob/master/init_mongo.js) used to bootstrap Mongo when the container starts. We're thinking the application will live in a new /cmd folder within this repo.
