### ISSUE TITLE
Go Bootstrapping -- Security Awareness

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/docker-edgex-mongo#33]
The Go bootstrapping application referred to in issue #32 needs to be aware of whether or not it's running in a context where security is enabled (the default) or disabled. It might make sense to do this via environment variables set in the relevant docker-compose file. Proposed environment variable would be `EDGEX_SECURITY=ON`. The absence of the variable would mean security is disabled. NOTE: This is currently a proposal I'm soliciting feedback on via Slack.

Would suggest for this issue to just implement the security branching logic for now. When security is ostensibly enabled, put some content into Mongo that you can verify the relevant initialization has run.

**Comment by difince** [comment]
Could this issue be assigned to me ?
