### ISSUE TITLE
Snyk Report shows high number of known CVEs with the docker-edgex-mongo image

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/docker-edgex-mongo#43]
Current number of CVE's found in the image based on the mongo:4.0-xenial image is 72 (40 high, 29 medium, 3 low).  
Per Snyk, we can reduce the risk by using the mongo:4.2.0-bionic image.

**Comment by difince** [comment]
Thank you @jamesrgregg . I will try it
