### ISSUE TITLE
Need to Upgrade ARM64 Dockerfile to use Mongo 4.2

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/docker-edgex-mongo#46]
The `Dockerfile.aarch64` needs to be upgraded as well to use Mongo 4.2 as we just did for `x86_64`. I'll tag @cloudxxx8 as well on this as his team has an easy way to test the changes.

**Comment by difince** [comment]
@tsconn23 This issue is not relvant anymore because `Dockerfile.aar64` does not exist anymore. It has been removed by  PR https://github.com/edgexfoundry/docker-edgex-mongo/pull/76

>  We are able to build the arm64 images using the same Dockerfile in the CI infrastructure. This is because mongo has released arm64 images under the same tag. We can now remove the duplication for the two Dockerfiles.
https://github.com/edgexfoundry/docker-edgex-mongo/pull/76#issuecomment-571409998

**Comment by difince** [comment]
This issue is not relevant anymore because Dockerfile.aar64 does not exist anymore. It has been removed by PR #76. See the comment above for more info
