### ISSUE TITLE
SecretStoreInfo struct should inherit from go-mod-secrets

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/docker-edgex-mongo#68]
edgex-go's usage of the SecretConfig struct is just that it inherits from go-mod-secrets struct:

https://github.com/edgexfoundry/edgex-go/blob/0916a3a8fe4a7b163a8af3aa1b000bcefd17920a/internal/pkg/config/types.go#L184-L189

We should do the same here so that we don't need to track all the details of go-mod-secrets here, we can just upgrade the version of go-mod-secrets used to build docker-edgex-mongo.

That would mean changes to the SecretStoreInfo struct here:

https://github.com/edgexfoundry/docker-edgex-mongo/blob/a0f626194ab6cb74fc2abb0a3feebe5de58b4799/internal/pkg/config.go#L55-L63

**Comment by tonyespy** [comment]
FYI, this also caused security configuration key values to change yet again between fuji & geneva. As discussed in today's Core WG meeting, we need to better articulate our policies wrt to configuration changes and major/minor versions of EdgeX.
