### ISSUE TITLE
launch-edgex-mongo.sh has an infinite loop

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/docker-edgex-mongo#8]
I found out the hard way while working on my edgex core snap that launch-edgex-mongo.sh can loop forever, and thus if hooked up to a native init script (eg. a systemd service) and the right conditions occur (ie. mongod fails to actually start), this script can cause a system hang.

The loop in this script should implement some sort of max retry limit, and then error out if triggered.

Also as an aside, the startup scripts in this repo are an example of edgex logic bound tightly to a specific deployment technology.  For my snap [1], I had to extract the launch and initialization scripts from this repository.

[1] https://github.com/tonyespy/edgex-core-snap/blob/master/snap/snapcraft.yaml#L185

**Comment by difince** [comment]
Because launch-edgex-mongo.sh does not exists anymore, and it does not contain an infinite loop (#36), I think the issue could be closed @tonyespy

**Comment by difince** [comment]
@tonyespy could you close this issue as not relevant anymore

**Comment by difince** [comment]
Closing the issue as being not relevant anymore. see comments above
